### ISSUE TITLE
Find new way to display screen on page

### ISSUE THREAD

**Issue by ghost** [bealkg/CurveStitchingSimulator#2]
Skulpt/Trinket won't work long-term, try react-turtle again, maybe an iframe?

**Comment by katherineb02** [comment]
react-turtle won't work - doesn't have stamp or dot functions so I can't make the points, also doesn't have the write function so I can't write point numbers.

**Comment by katherineb02** [comment]
Trinket is crazy slow and I don't think there will be a way to connect backend to front end
